### ISSUE TITLE
If the undoManager is not enabled, the onModelChange callback does not work

### ISSUE THREAD

**Issue by nicolaserny** [NorthwoodsSoftware/gojs-react-basic#1]
If the undoManager is not enabled, the onModelChange callback does not work anymore.

I notice that the undoManager is enabled in every example ([https://gojs.net/latest/intro/react.html](https://gojs.net/latest/intro/react.html)
Is there a reason or is it a bug?

**Comment by WalterNorthwoods** [comment]
The operation of the **UndoManager** is not necessary if the diagram is read-only.  But if the diagram and model might change and if you want to be notified of all of the changes via **DiagramProps.onModelChange**, then the component needs a complete history of all of the changes that occurred during the transaction.  That history is available as the **Transaction.changes** list, which is summarized by the call to **Model.toIncrementalData**.

**Comment by nicolaserny** [comment]
Thanks for the quick answer

**Comment by WalterNorthwoods** [comment]
I forgot to mention that if you do not want the user perform undo or redo, you can override **CommandHandler.undo** and **CommandHandler.redo** to be no-ops:
```
$(go.Diagram, . . .,
  { . . .,
    "undoManager.isEnabled": true,
    "commandHandler.undo": function() {},
    "commandHandler.redo": function() {}
  })
```

And if you want to limit how much memory is used by the **UndoManager**, you can set its **UndoManager.maxHistoryLength** to 1:
```
$(go.Diagram, . . .,
  { . . .,
    "undoManager.isEnabled": true,
    "undoManager.maxHistoryLength": 1
  })
```

**Comment by WalterNorthwoods** [comment]
With GoJS version 2.0.3 or later you can set **UndoManager.maxHistoryLength** to zero.  This will continue to support notifications at the end of transactions, but will not retain any history, which thereby disables undo and redo.
