### ISSUE TITLE
 clone gojs-react-basic  project, when i use a list data  in nodeDataArray, "Maximum update depth exceeded" happen, how can i fix this???

### ISSUE THREAD

**Issue by lence-wl** [NorthwoodsSoftware/gojs-react-basic#18]
this.state = {
			nodeDataArray: [
				{ key: 0, text: "Alpha", color: "lightblue", loc: "0 0", strokeDashArray: [10, 20] },
				{ key: 1, text: "Beta", color: "orange", loc: "150 0", strokeDashArray: [10, 20] },
				{ key: 2, text: "Gamma", color: "lightgreen", loc: "0 150", strokeDashArray: [10, 20] },
				{ key: 3, text: "Delta", color: "pink", loc: "150 150", strokeDashArray: [10, 20] },
			],
			linkDataArray: [
				{ key: -1, from: 0, to: 1 },
				{ key: -2, from: 0, to: 2 },
				{ key: -3, from: 1, to: 1 },
				{ key: -4, from: 2, to: 3 },
				{ key: -5, from: 3, to: 0 },
			],
			modelData: {
				canRelink: true,
			},
			selectedData: null,
			skipsDiagramUpdate: false,
		};

**Comment by jonchardy** [comment]
We're looking into this.

**Comment by jonchardy** [comment]
This was a problem of creating a new object to pass in as a style on every render. We've fixed this.

https://github.com/NorthwoodsSoftware/gojs-react-basic/commit/8ae5ed1d52ee86d5de85f8a04a24951b223b7f3a#diff-501ae4fb4e1c0567b744b8a4cbb70a32a7448ee068412482cc13147c7a8e1d6e
