### ISSUE TITLE
get model data after change event

### ISSUE THREAD

**Issue by tommybernaciak** [NorthwoodsSoftware/gojs-react-basic#2]
Is this possible to get model data after the diagram is changed? What I try to do is handle `onModelChange` event for `ReactDiagram` component. It returns data of `go.IncrementalData` type which should return me `modelData` but I never receive it. I receive all other properties like `insertedNodeKeys`, `modifiedNodeData` etc. I could build up an updated model using those data but I assume that model should be already available using `modelData` property, am I right?

**Comment by WalterNorthwoods** [comment]
The IncrementalData will include a "modelData" property only if the **Model.modelData** shared object had been modified.  https://gojs.net/latest/api/symbols/Model.html#modelData
