### ISSUE TITLE
TypeError: Cannot add property __gohashid, object is not extensible

### ISSUE THREAD

**Issue by drenther** [NorthwoodsSoftware/gojs-react-basic#4]
## Error description
Error when making any changes in the inspector or toggling relink input and then interacting with the diagram canvas again.

## Steps to reproduce
![Kapture 2020-02-12 at 14 50 28](https://user-images.githubusercontent.com/12991390/74320912-740b5b80-4da7-11ea-95e8-d98cefe72ba9.gif)

Took the liberty of using this repo as a template in codesandbox - https://codesandbox.io/s/github/NorthwoodsSoftware/gojs-react-basic

**Comment by jonchardy** [comment]
I see the problem in CodeSandbox, but I'm unable to reproduce it outside that environment. Do you have the same problem if you download the repo and install/run?

**Comment by drenther** [comment]
No. That's very weird. Thanks for responding so quickly. Might be some issue with how codesandbox handles updates.
